/*
 * benchtab.h: List of benchmarks.
 *
 * Copyright (C) 2011 Mikhail Kurnosov
 */

#ifndef BENCHTAB_H
#define BENCHTAB_H

bench_t benchtab[] = {
    {
      "Barrier", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_barrier_printinfo,
      (bench_init_ptr_t)bench_barrier_init,
      (bench_free_ptr_t)bench_barrier_free,
      (bench_init_test_ptr_t)bench_barrier_init_test,
      (bench_free_test_ptr_t)bench_barrier_free_test,
      (measure_ptr_t)measure_barrier_sync,
      (getcomm_ptr_t)commseq_getcomm,
      (getcommsize_ptr_t)commseq_getcommsize,
      (getrank_ptr_t)commseq_getcommrank,
      "Comm", commseq_getcurrent, commseq_getnext, commseq_getsize,
      commseq_reset
    },
    {
      "Bcast", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_bcast_printinfo,
      (bench_init_ptr_t)bench_bcast_init,
      (bench_free_ptr_t)bench_bcast_free,
      (bench_init_test_ptr_t)bench_bcast_init_test,
      (bench_free_test_ptr_t)bench_bcast_free_test,
      (measure_ptr_t)measure_bcast_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Gather", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_gather_printinfo,
      (bench_init_ptr_t)bench_gather_init,
      (bench_free_ptr_t)bench_gather_free,
      (bench_init_test_ptr_t)bench_gather_init_test,
      (bench_free_test_ptr_t)bench_gather_free_test,
      (measure_ptr_t)measure_gather_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Scatter", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_scatter_printinfo,
      (bench_init_ptr_t)bench_scatter_init,
      (bench_free_ptr_t)bench_scatter_free,
      (bench_init_test_ptr_t)bench_scatter_init_test,
      (bench_free_test_ptr_t)bench_scatter_free_test,
      (measure_ptr_t)measure_scatter_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Allgather", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_allgather_printinfo,
      (bench_init_ptr_t)bench_allgather_init,
      (bench_free_ptr_t)bench_allgather_free,
      (bench_init_test_ptr_t)bench_allgather_init_test,
      (bench_free_test_ptr_t)bench_allgather_free_test,
      (measure_ptr_t)measure_allgather_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "SendCount", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Alltoall", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_alltoall_printinfo,
      (bench_init_ptr_t)bench_alltoall_init,
      (bench_free_ptr_t)bench_alltoall_free,
      (bench_init_test_ptr_t)bench_alltoall_init_test,
      (bench_free_test_ptr_t)bench_alltoall_free_test,
      (measure_ptr_t)measure_alltoall_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Reduce", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_reduce_printinfo,
      (bench_init_ptr_t)bench_reduce_init,
      (bench_free_ptr_t)bench_reduce_free,
      (bench_init_test_ptr_t)bench_reduce_init_test,
      (bench_free_test_ptr_t)bench_reduce_free_test,
      (measure_ptr_t)measure_reduce_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Allreduce", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_allreduce_printinfo,
      (bench_init_ptr_t)bench_allreduce_init,
      (bench_free_ptr_t)bench_allreduce_free,
      (bench_init_test_ptr_t)bench_allreduce_init_test,
      (bench_free_test_ptr_t)bench_allreduce_free_test,
      (measure_ptr_t)measure_allreduce_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
/*
    {
      "Reduce_scatter_block", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_reduce_scatter_block_printinfo,
      (bench_init_ptr_t)bench_reduce_scatter_block_init,
      (bench_free_ptr_t)bench_reduce_scatter_block_free,
      (bench_init_test_ptr_t)bench_reduce_scatter_block_init_test,
      (bench_free_test_ptr_t)bench_reduce_scatter_block_free_test,
      (measure_ptr_t)measure_reduce_scatter_block_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
*/
    {
      "Reduce_scatter", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_reduce_scatter_printinfo,
      (bench_init_ptr_t)bench_reduce_scatter_init,
      (bench_free_ptr_t)bench_reduce_scatter_free,
      (bench_init_test_ptr_t)bench_reduce_scatter_init_test,
      (bench_free_test_ptr_t)bench_reduce_scatter_free_test,
      (measure_ptr_t)measure_reduce_scatter_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Scan", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_scan_printinfo,
      (bench_init_ptr_t)bench_scan_init,
      (bench_free_ptr_t)bench_scan_free,
      (bench_init_test_ptr_t)bench_scan_init_test,
      (bench_free_test_ptr_t)bench_scan_free_test,
      (measure_ptr_t)measure_scan_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Exscan", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_exscan_printinfo,
      (bench_init_ptr_t)bench_exscan_init,
      (bench_free_ptr_t)bench_exscan_free,
      (bench_init_test_ptr_t)bench_exscan_init_test,
      (bench_free_test_ptr_t)bench_exscan_free_test,
      (measure_ptr_t)measure_exscan_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Gatherv", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_gatherv_printinfo,
      (bench_init_ptr_t)bench_gatherv_init,
      (bench_free_ptr_t)bench_gatherv_free,
      (bench_init_test_ptr_t)bench_gatherv_init_test,
      (bench_free_test_ptr_t)bench_gatherv_free_test,
      (measure_ptr_t)measure_gatherv_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Scatterv", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_scatterv_printinfo,
      (bench_init_ptr_t)bench_scatterv_init,
      (bench_free_ptr_t)bench_scatterv_free,
      (bench_init_test_ptr_t)bench_scatterv_init_test,
      (bench_free_test_ptr_t)bench_scatterv_free_test,
      (measure_ptr_t)measure_scatterv_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Alltoallv", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_alltoallv_printinfo,
      (bench_init_ptr_t)bench_alltoallv_init,
      (bench_free_ptr_t)bench_alltoallv_free,
      (bench_init_test_ptr_t)bench_alltoallv_init_test,
      (bench_free_test_ptr_t)bench_alltoallv_free_test,
      (measure_ptr_t)measure_alltoallv_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Allgatherv", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_allgatherv_printinfo,
      (bench_init_ptr_t)bench_allgatherv_init,
      (bench_free_ptr_t)bench_allgatherv_free,
      (bench_init_test_ptr_t)bench_allgatherv_init_test,
      (bench_free_test_ptr_t)bench_allgatherv_free_test,
      (measure_ptr_t)measure_allgatherv_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Alltoallw", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_alltoallw_printinfo,
      (bench_init_ptr_t)bench_alltoallw_init,
      (bench_free_ptr_t)bench_alltoallw_free,
      (bench_init_test_ptr_t)bench_alltoallw_init_test,
      (bench_free_test_ptr_t)bench_alltoallw_free_test,
      (measure_ptr_t)measure_alltoallw_sync,
      (getcomm_ptr_t)getcommworld,
      (getcommsize_ptr_t)getcommworld_size,
      (getrank_ptr_t)getcommworld_rank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "WaitPatternUp", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_waitpatternup_printinfo,
      (bench_init_ptr_t)bench_waitpattern_init,
      (bench_free_ptr_t)bench_waitpattern_free,
      (bench_init_test_ptr_t)bench_waitpattern_init_test,
      (bench_free_test_ptr_t)bench_waitpattern_free_test,
      (measure_ptr_t)measure_waitpatternup_sync,
      (getcomm_ptr_t)commseq_getcomm,
      (getcommsize_ptr_t)commseq_getcommsize,
      (getrank_ptr_t)commseq_getcommrank,
      "Commsize", commseq_getcurrent, commseq_getnext, commseq_getsize,
      commseq_reset
    },
    {
      "WaitPatternDown", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_waitpatterndown_printinfo,
      (bench_init_ptr_t)bench_waitpattern_init,
      (bench_free_ptr_t)bench_waitpattern_free,
      (bench_init_test_ptr_t)bench_waitpattern_init_test,
      (bench_free_test_ptr_t)bench_waitpattern_free_test,
      (measure_ptr_t)measure_waitpatterndown_sync,
      (getcomm_ptr_t)commseq_getcomm,
      (getcommsize_ptr_t)commseq_getcommsize,
      (getrank_ptr_t)commseq_getcommrank,
      "Commsize", commseq_getcurrent, commseq_getnext, commseq_getsize,
      commseq_reset
    },
    {
      "WaitPatternNull", MPIFUNC_TYPE_COLL,
      (printinfo_ptr_t)bench_waitpatternnull_printinfo,
      (bench_init_ptr_t)bench_waitpattern_init,
      (bench_free_ptr_t)bench_waitpattern_free,
      (bench_init_test_ptr_t)bench_waitpattern_init_test,
      (bench_free_test_ptr_t)bench_waitpattern_free_test,
      (measure_ptr_t)measure_waitpatternnull_sync,
      (getcomm_ptr_t)commseq_getcomm,
      (getcommsize_ptr_t)commseq_getcommsize,
      (getrank_ptr_t)commseq_getcommrank,
      "Commsize", commseq_getcurrent, commseq_getnext, commseq_getsize,
      commseq_reset
    },
    {
      "Sendrecv", MPIFUNC_TYPE_PT2PT,
      (printinfo_ptr_t)bench_sendrecv_printinfo,
      (bench_init_ptr_t)bench_sendrecv_init,
      (bench_free_ptr_t)bench_sendrecv_free,
      (bench_init_test_ptr_t)bench_sendrecv_init_test,
      (bench_free_test_ptr_t)bench_sendrecv_free_test,
      (measure_ptr_t)measure_sendrecv_sync,
      (getcomm_ptr_t)bench_sendrecv_getcomm,
      (getcommsize_ptr_t)bench_sendrecv_getcommsize,
      (getrank_ptr_t)bench_sendrecv_getcommrank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    },
    {
      "Send", MPIFUNC_TYPE_PT2PT,
      (printinfo_ptr_t)bench_send_printinfo,
      (bench_init_ptr_t)bench_send_init,
      (bench_free_ptr_t)bench_send_free,
      (bench_init_test_ptr_t)bench_send_init_test,
      (bench_free_test_ptr_t)bench_send_free_test,
      (measure_ptr_t)measure_send_sync,
      (getcomm_ptr_t)bench_send_getcomm,
      (getcommsize_ptr_t)bench_send_getcommsize,
      (getrank_ptr_t)bench_send_getcommrank,
      "Count", intseq_getcurrent, intseq_getnext, intseq_getsize,
      intseq_reset
    }
};

#endif /* BENCHTAB_H */

